//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public Complaint(int id, string status, int serviceQ, int quickR, int customerQ, string shortDescription, string longDescription, int clientId)
        {
            this.id = id;
            this.status = status;
            this.serviceQ = serviceQ;
            this.quickR = quickR;
            this.customerQ = customerQ;
            this.shortDescription = shortDescription;
            this.longDescription = longDescription;
            this.clientId = clientId;
        }
        public Complaint()
        {

        }

        public int id { get; set; }
        public string status { get; set; }
        public int serviceQ { get; set; }
        public int quickR { get; set; }
        public int customerQ { get; set; }
        public string shortDescription { get; set; }
        public string longDescription { get; set; }
        public int clientId { get; set; }
    }
}
