//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User(int id, string rights, string registrationNr, string name, string password)
        {
            this.id = id;
            this.rights = rights;
            this.registrationNr = registrationNr;
            this.name = name;
            this.password = password;
        }
        public User()
        {

        }
        public int id { get; set; }
        public string rights { get; set; }
        public string registrationNr { get; set; }
        public string name { get; set; }
        public string password { get; set; }
    }
}
